##### Example code for generating coefficient plots, e.g. as per Fig. 3 Main text. 

## Ruth Kelly (kellyr44@tcd.ie) 01/08/2017 

## For "Contrasting impacts of high priority invasive plant species on pollinating insect communities"
## Based on data collected by Emily Davis, study design by Emily Davis, Jane Stout and Christine Maggs

## Note: small changes were made to plots using Serif Drawplus before publication (i.e. fonts/text positions)
## This code replicates the core of the figure based on data files generated by the analysis scripts 
## "GH_only_polly_analysis_01_08_2017.R", "JK_only_polly_analysis_01_08_2017.R"  and "HB_only_polly_analysis_01_08_2017.R"
## For Giant hogweed, Japanese knotweed and Himalayan Balsam datasets respectively.

library("ggplot2")


GH_mods <- read.csv("GH_abundance_impact_results_01_08_2017.csv")
HB_mods <- read.csv("HB_abundance_impact_results_01_08_2017.csv")
JK_mods <- read.csv("JK_abundance_impact_results_01_08_2017.csv")

All_mods <- rbind(GH_mods, HB_mods, JK_mods)

str(All_mods)

All_mods$Species

All_mods$SpeciesLatin <- c(rep("H.m.", 4), rep("I.g", 5), rep("F.j.", 4) )

table(All_mods$SpeciesLatin,All_mods$modelName)

All_mods$modelNameOrder <- factor(All_mods$modelName, 
                                  levels = c("Bumblebee abundance",
                                             "Honey bee abundance",
                                             "Hoverfly abundance",
                                             "Solitary bee abundance", 
                                             "Total pollinator abundance")) 
levels(All_mods$modelNameOrder)


zp1 <- ggplot(All_mods, aes(colour = SpeciesLatin, shape = SpeciesLatin))
zp1 <- zp1 + geom_hline(yintercept = 0, colour = gray(1/4), lty = 2)
zp1 <- zp1 + geom_pointrange(aes(x = modelNameOrder, y = Coefficient, 
                                 ymin = Confint_L,
                                 ymax = Confint_U),show.legend=T,
                             lwd = 0.5, position = position_dodge(width = 2/3))
zp1 <- zp1 + coord_flip() + theme_bw()
zp1 <- zp1 + theme(axis.title.y=element_blank())
zp1 <- zp1 + scale_colour_manual(values = c("dark red", "tomato2", "goldenrod1"))
zp1 <- zp1 + theme(legend.text = element_text(face = "italic", size = 8))
zp1 <- zp1 + theme(axis.text.x = element_text(size = 8))
zp1 <- zp1 + theme(axis.text.y = element_text(size = 8))
zp1 <- zp1 + theme(axis.title.x = element_text(size = 8))
zp1 <- zp1 + theme(plot.title = element_text(size = 11))
zp1 <- zp1 + guides(colour = guide_legend(title = NULL))
zp1 <- zp1 + guides(shape = guide_legend(title = NULL))
zp1 <- zp1 + ggtitle("Insect abundance")

##################
